Repository compsci-adl/cms, pull requests merged in 2025-07, with the labels that each got.

#19 feat: Add photo galleries for events
  src/collections/Gallery.ts
  src/collections/Media.ts
  src/payload-types.ts
  src/payload.config.ts
Labels: enhancement, collection

#20 feat: Resize images with metadata extraction
  src/collections/Media.ts
Labels: enhancement

#23 fix: Bulk media uploads
  package.json
  pnpm-lock.yaml
  src/collections/Media.ts
Labels: enhancement

#24 fix: Support WebP format for media uploads and slugify filenames
  src/collections/Media.ts
Labels: enhancement

#25 feat(gallery): Auto add media for galleries
  src/collections/Gallery.ts
Labels: enhancement, collection

#27 feat: Add Environment Variable for Login Type Switching
  .env.example
  src/payload.config.ts
Labels: documentation, enhancement

#28 chore(gallery): Add support for HEIF/HEIC images
  README.md
  compress-images.py
  requirements.txt
Labels: enhancement
